//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJCP.Core.Environment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJCP.Core.Environment.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an OSVersion.
        /// </summary>
        internal static string ArgumentEx_NotOsVersion {
            get {
                return ResourceManager.GetString("ArgumentEx_NotOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set &apos;{0}&apos; on Sealed instance.
        /// </summary>
        internal static string InvalidOperationEx_CheckLock {
            get {
                return ResourceManager.GetString("InvalidOperationEx_CheckLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error: Must get OS version information first.
        /// </summary>
        internal static string InvalidOperationEx_InternalGetOsVersion {
            get {
                return ResourceManager.GetString("InvalidOperationEx_InternalGetOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework v{0}, Mono Runtime v{1} {2}.
        /// </summary>
        internal static string Mono {
            get {
                return ResourceManager.GetString("Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework v{0}, Mono Runtime {1}.
        /// </summary>
        internal static string MonoNoVersion {
            get {
                return ResourceManager.GetString("MonoNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.5.
        /// </summary>
        internal static string Net45 {
            get {
                return ResourceManager.GetString("Net45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown .NET version before .NET 4.5 ({0}).
        /// </summary>
        internal static string Net45_Unknown {
            get {
                return ResourceManager.GetString("Net45_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.5.1 installed on Windows 8, Windows 7 SP1, or Windows Vista SP2.
        /// </summary>
        internal static string Net451_Vista {
            get {
                return ResourceManager.GetString("Net451_Vista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.5.1 installed with Windows 8.1 or Windows Server 2012 R2.
        /// </summary>
        internal static string Net451_Win81 {
            get {
                return ResourceManager.GetString("Net451_Win81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.5.2.
        /// </summary>
        internal static string Net452 {
            get {
                return ResourceManager.GetString("Net452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.
        /// </summary>
        internal static string Net46 {
            get {
                return ResourceManager.GetString("Net46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6 on Windows 10 (1507).
        /// </summary>
        internal static string Net46_Win10 {
            get {
                return ResourceManager.GetString("Net46_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.1.
        /// </summary>
        internal static string Net461 {
            get {
                return ResourceManager.GetString("Net461", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.1 on Windows 10, November Update (1511).
        /// </summary>
        internal static string Net461_Win10 {
            get {
                return ResourceManager.GetString("Net461_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.2.
        /// </summary>
        internal static string Net462 {
            get {
                return ResourceManager.GetString("Net462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.6.2 on Windows 10, Anniversary Update (1607) or Windows Server 2016.
        /// </summary>
        internal static string Net462_Win10 {
            get {
                return ResourceManager.GetString("Net462_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7.
        /// </summary>
        internal static string Net47 {
            get {
                return ResourceManager.GetString("Net47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7 on Windows 10, Creators Update (1703).
        /// </summary>
        internal static string Net47_Win10 {
            get {
                return ResourceManager.GetString("Net47_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7.1.
        /// </summary>
        internal static string Net471 {
            get {
                return ResourceManager.GetString("Net471", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7.1 on Windows 10, Fall Creators Update (1709).
        /// </summary>
        internal static string Net471_Win10 {
            get {
                return ResourceManager.GetString("Net471_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7.2.
        /// </summary>
        internal static string Net472 {
            get {
                return ResourceManager.GetString("Net472", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.7.2 on Windows 10, Spring Creators Update (1803).
        /// </summary>
        internal static string Net472_Win10 {
            get {
                return ResourceManager.GetString("Net472_Win10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8.
        /// </summary>
        internal static string Net48 {
            get {
                return ResourceManager.GetString("Net48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8 on Windows 10, May 2019 Update (1903).
        /// </summary>
        internal static string Net48_Win10_1903 {
            get {
                return ResourceManager.GetString("Net48_Win10_1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8 on Windows 10, October 2019 Update (1909).
        /// </summary>
        internal static string Net48_Win10_1909 {
            get {
                return ResourceManager.GetString("Net48_Win10_1909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8 on Windows 10, October 2020 Update (20H2, 21H1).
        /// </summary>
        internal static string Net48_Win10_20H2 {
            get {
                return ResourceManager.GetString("Net48_Win10_20H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8 on Windows 11 / Server 2022.
        /// </summary>
        internal static string Net48_Win11 {
            get {
                return ResourceManager.GetString("Net48_Win11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8.1.
        /// </summary>
        internal static string Net481 {
            get {
                return ResourceManager.GetString("Net481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4.8.1 on Windows 11 22H2.
        /// </summary>
        internal static string Net481_Win11_22H2 {
            get {
                return ResourceManager.GetString("Net481_Win11_22H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET {0} or later, release {1}.
        /// </summary>
        internal static string NetFx {
            get {
                return ResourceManager.GetString("NetFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework v{0}, Release {1} ({2}).
        /// </summary>
        internal static string NetFx45Details {
            get {
                return ResourceManager.GetString("NetFx45Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} {1}.
        /// </summary>
        internal static string NetFxDetails {
            get {
                return ResourceManager.GetString("NetFxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework.
        /// </summary>
        internal static string NetFxLegacy {
            get {
                return ResourceManager.GetString("NetFxLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string NetFxLegacyProfile {
            get {
                return ResourceManager.GetString("NetFxLegacyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        internal static string NetFxLegacySp {
            get {
                return ResourceManager.GetString("NetFxLegacySp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Environment Runtime.
        /// </summary>
        internal static string NetFxRuntime {
            get {
                return ResourceManager.GetString("NetFxRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinVersionQuery is only supported on Windows.
        /// </summary>
        internal static string PlatformNotSupportedEx {
            get {
                return ResourceManager.GetString("PlatformNotSupportedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVersionEx() failure. Error = 0x{0:8x}.
        /// </summary>
        internal static string Win32Ex_GetVersionEx {
            get {
                return ResourceManager.GetString("Win32Ex_GetVersionEx", resourceCulture);
            }
        }
    }
}
